//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.http.data.response.GetBannerResponse.Banner;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import com.internet.view.CircleImageView;
import com.internet.view.MainBottomItemView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainAct_
    extends MainAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_main);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainAct_.IntentBuilder_ intent(Context context) {
        return new MainAct_.IntentBuilder_(context);
    }

    public static MainAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MainAct_.IntentBuilder_(fragment);
    }

    public static MainAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MainAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_bottom_order = ((MainBottomItemView) hasViews.findViewById(id.text_bottom_order));
        text_bottom_income = ((MainBottomItemView) hasViews.findViewById(id.text_bottom_income));
        text_bottom_home = ((MainBottomItemView) hasViews.findViewById(id.text_bottom_home));
        text_bottom_exam = ((MainBottomItemView) hasViews.findViewById(id.text_bottom_exam));
        text_tip = ((TextView) hasViews.findViewById(id.text_tip));
        image_header = ((CircleImageView) hasViews.findViewById(id.image_header));
        {
            View view = hasViews.findViewById(id.text_my_income);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.myIncome();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_bottom_income);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.myIncome();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_make_order);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.makeOrder();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_bottom_order);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.makeOrder();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_message);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.clickTip();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.image_header);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.imagePhoto();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_site);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.realseInfor(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_road);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.realseInfor(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_escort);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.realseInfor(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_bottom_exam);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.makeExam();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_bottom_home);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.home();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_my_student);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainAct_.this.myStudent();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void goPublic(final String typeCode) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.goPublic(typeCode);
            }

        }
        );
    }

    @Override
    public void showMessageQuntity(final int quntity) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showMessageQuntity(quntity);
            }

        }
        );
    }

    @Override
    public void showHead(final boolean isShow, final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showHead(isShow, bitmap);
            }

        }
        );
    }

    @Override
    public void inflatePageView(final ArrayList<Banner> result) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.inflatePageView(result);
            }

        }
        );
    }

    @Override
    public void goToLogin() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.goToLogin();
            }

        }
        );
    }

    @Override
    public void showPageItem(final ImageView imageView, final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainAct_.super.showPageItem(imageView, bitmap);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void findUser2(final String typeCode) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.findUser2(typeCode);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void findUser() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.findUser();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getBitmap(final String url, final ImageView imageView) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.getBitmap(url, imageView);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void showHead() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.showHead();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getMessageQuntity() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.getMessageQuntity();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getBanner() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainAct_.super.getBanner();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MainAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MainAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MainAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MainAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
