//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import android.widget.TextView;
import com.internet.entity.OrderEntity;
import com.internet.http.api.ApiException;
import com.internet.http.data.response.GetOrderCalendarResponse.OrderCalendar;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderMainAct_
    extends OrderMainAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_order_main);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderMainAct_.IntentBuilder_ intent(Context context) {
        return new OrderMainAct_.IntentBuilder_(context);
    }

    public static OrderMainAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new OrderMainAct_.IntentBuilder_(fragment);
    }

    public static OrderMainAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new OrderMainAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_no_data = ((TextView) hasViews.findViewById(id.text_no_data));
        mListView = ((ListView) hasViews.findViewById(id.mListView));
        init();
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void hideEmpoty() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.hideEmpoty();
            }

        }
        );
    }

    @Override
    public void showOrderList(final ArrayList<OrderEntity> result) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.showOrderList(result);
            }

        }
        );
    }

    @Override
    public void initDateTitle(final ArrayList<OrderCalendar> list) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.initDateTitle(list);
            }

        }
        );
    }

    @Override
    public void showEmpoty() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderMainAct_.super.showEmpoty();
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderMainAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doQueryOrderList(final String date) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderMainAct_.super.doQueryOrderList(date);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getOrderCalendar() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderMainAct_.super.getOrderCalendar();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, OrderMainAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderMainAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderMainAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public OrderMainAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
