//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.http.data.vo.OrderDetailVO;
import com.internet.qianyue.R.id;
import com.internet.qianyue.R.layout;
import com.internet.view.CircleImageView;
import com.internet.view.HeaderView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderDetailAct_
    extends OrderDetailAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_order_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderDetailAct_.IntentBuilder_ intent(Context context) {
        return new OrderDetailAct_.IntentBuilder_(context);
    }

    public static OrderDetailAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new OrderDetailAct_.IntentBuilder_(fragment);
    }

    public static OrderDetailAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new OrderDetailAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_phone = ((TextView) hasViews.findViewById(id.text_phone));
        text_1_1 = ((TextView) hasViews.findViewById(id.text_1_1));
        text_1_4 = ((TextView) hasViews.findViewById(id.text_1_4));
        text_2_3 = ((TextView) hasViews.findViewById(id.text_2_3));
        text_2_2 = ((TextView) hasViews.findViewById(id.text_2_2));
        text_2_1 = ((TextView) hasViews.findViewById(id.text_2_1));
        text_1_3 = ((TextView) hasViews.findViewById(id.text_1_3));
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        image_phone = ((ImageView) hasViews.findViewById(id.image_phone));
        text_1_2 = ((TextView) hasViews.findViewById(id.text_1_2));
        text_name = ((TextView) hasViews.findViewById(id.text_name));
        image_photo = ((CircleImageView) hasViews.findViewById(id.image_photo));
        {
            View view = hasViews.findViewById(id.image_phone);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderDetailAct_.this.clickCallPhone();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderDetailAct_.this.clickSave();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void showLoading(final String tip) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.showLoading(tip);
            }

        }
        );
    }

    @Override
    public void showToast(final String content) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.showToast(content);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean enable) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.fullScreen(enable);
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException ex) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.onApiException(ex);
            }

        }
        );
    }

    @Override
    public void refreshViews(final OrderDetailVO orderDetailVO) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.refreshViews(orderDetailVO);
            }

        }
        );
    }

    @Override
    public void showHead(final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderDetailAct_.super.showHead(bitmap);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderDetailAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void showHead(final String url) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderDetailAct_.super.showHead(url);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void takeInOrder() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderDetailAct_.super.takeInOrder();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getOrderDetail() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderDetailAct_.super.getOrderDetail();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, OrderDetailAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderDetailAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderDetailAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public OrderDetailAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
