//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import com.internet.view.HeaderView;
import com.internet.view.ImageTextView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RegistDspAct_
    extends RegistDspAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_regist_dsp);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RegistDspAct_.IntentBuilder_ intent(Context context) {
        return new RegistDspAct_.IntentBuilder_(context);
    }

    public static RegistDspAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new RegistDspAct_.IntentBuilder_(fragment);
    }

    public static RegistDspAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new RegistDspAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        image_text_2 = ((ImageTextView) hasViews.findViewById(id.image_text_2));
        edit_no = ((EditText) hasViews.findViewById(id.edit_no));
        image_text_4 = ((ImageTextView) hasViews.findViewById(id.image_text_4));
        edit_school = ((EditText) hasViews.findViewById(id.edit_school));
        edit_old = ((EditText) hasViews.findViewById(id.edit_old));
        image_text_1 = ((ImageTextView) hasViews.findViewById(id.image_text_1));
        edit_area = ((TextView) hasViews.findViewById(id.edit_area));
        image_text_6 = ((ImageTextView) hasViews.findViewById(id.image_text_6));
        edit_model = ((TextView) hasViews.findViewById(id.edit_model));
        edit_name = ((EditText) hasViews.findViewById(id.edit_name));
        edit_address = ((EditText) hasViews.findViewById(id.edit_address));
        image_text_3 = ((ImageTextView) hasViews.findViewById(id.image_text_3));
        image_text_5 = ((ImageTextView) hasViews.findViewById(id.image_text_5));
        {
            View view = hasViews.findViewById(id.btn_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RegistDspAct_.this.save();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RegistDspAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    RegistDspAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RegistDspAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, RegistDspAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, RegistDspAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RegistDspAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
