//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.qianyue.R.id;
import com.internet.qianyue.R.layout;
import com.internet.view.HeaderView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ReleaseSelectTimeDefaultAct_
    extends ReleaseSelectTimeDefaultAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_release_select_time_default);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ReleaseSelectTimeDefaultAct_.IntentBuilder_ intent(Context context) {
        return new ReleaseSelectTimeDefaultAct_.IntentBuilder_(context);
    }

    public static ReleaseSelectTimeDefaultAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ReleaseSelectTimeDefaultAct_.IntentBuilder_(fragment);
    }

    public static ReleaseSelectTimeDefaultAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ReleaseSelectTimeDefaultAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text2 = ((TextView) hasViews.findViewById(id.text2));
        edit_price = ((EditText) hasViews.findViewById(id.edit_price));
        text4 = ((TextView) hasViews.findViewById(id.text4));
        check5 = ((CheckBox) hasViews.findViewById(id.check5));
        check6 = ((CheckBox) hasViews.findViewById(id.check6));
        text3 = ((TextView) hasViews.findViewById(id.text3));
        text1 = ((TextView) hasViews.findViewById(id.text1));
        check3 = ((CheckBox) hasViews.findViewById(id.check3));
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        text6 = ((TextView) hasViews.findViewById(id.text6));
        check1 = ((CheckBox) hasViews.findViewById(id.check1));
        text5 = ((TextView) hasViews.findViewById(id.text5));
        check4 = ((CheckBox) hasViews.findViewById(id.check4));
        check2 = ((CheckBox) hasViews.findViewById(id.check2));
        {
            View view = hasViews.findViewById(id.btn_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ReleaseSelectTimeDefaultAct_.this.clickSave();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void showToast(final String content) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.showToast(content);
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean enable) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.fullScreen(enable);
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void showLoading(final String tip) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.showLoading(tip);
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException ex) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.onApiException(ex);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void exit() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ReleaseSelectTimeDefaultAct_.super.exit();
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ReleaseSelectTimeDefaultAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doRelease() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ReleaseSelectTimeDefaultAct_.super.doRelease();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ReleaseSelectTimeDefaultAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ReleaseSelectTimeDefaultAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ReleaseSelectTimeDefaultAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ReleaseSelectTimeDefaultAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
