//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemSelectedListener;
import android.widget.Spinner;
import com.internet.http.api.ApiException;
import com.internet.http.data.vo.AreaVO;
import com.internet.turnright.b.R.layout;
import com.internet.view.HeaderView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SelfInfoSelectCityAct_
    extends SelfInfoSelectCityAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_self_info_select_city);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelfInfoSelectCityAct_.IntentBuilder_ intent(Context context) {
        return new SelfInfoSelectCityAct_.IntentBuilder_(context);
    }

    public static SelfInfoSelectCityAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SelfInfoSelectCityAct_.IntentBuilder_(fragment);
    }

    public static SelfInfoSelectCityAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SelfInfoSelectCityAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mProvince = ((Spinner) hasViews.findViewById(com.internet.turnright.b.R.id.mProvince));
        mCity = ((Spinner) hasViews.findViewById(com.internet.turnright.b.R.id.mCity));
        mArea = ((Spinner) hasViews.findViewById(com.internet.turnright.b.R.id.mArea));
        view_header = ((HeaderView) hasViews.findViewById(com.internet.turnright.b.R.id.view_header));
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.internet.turnright.b.R.id.mCity));
            if (view!= null) {
                view.setOnItemSelectedListener(new OnItemSelectedListener() {


                    @Override
                    public void onNothingSelected(AdapterView<?> parent) {
                        itemSelectCity(false, -1);
                    }

                    @Override
                    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                        SelfInfoSelectCityAct_.this.itemSelectCity(true, position);
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.internet.turnright.b.R.id.mProvince));
            if (view!= null) {
                view.setOnItemSelectedListener(new OnItemSelectedListener() {


                    @Override
                    public void onNothingSelected(AdapterView<?> parent) {
                        itemSelectProvince(false, -1);
                    }

                    @Override
                    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                        SelfInfoSelectCityAct_.this.itemSelectProvince(true, position);
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.internet.turnright.b.R.id.mArea));
            if (view!= null) {
                view.setOnItemSelectedListener(new OnItemSelectedListener() {


                    @Override
                    public void onNothingSelected(AdapterView<?> parent) {
                        itemSelectArea(false, -1);
                    }

                    @Override
                    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                        SelfInfoSelectCityAct_.this.itemSelectArea(true, position);
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void showCity(final ArrayList<AreaVO> listCityVO) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showCity(listCityVO);
            }

        }
        );
    }

    @Override
    public void showProvince(final ArrayList<AreaVO> listProviceVO) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showProvince(listProviceVO);
            }

        }
        );
    }

    @Override
    public void showArea(final ArrayList<AreaVO> listAreaVO) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoSelectCityAct_.super.showArea(listAreaVO);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoSelectCityAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getArea(final String regionId, final int type) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoSelectCityAct_.super.getArea(regionId, type);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelfInfoSelectCityAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfInfoSelectCityAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfInfoSelectCityAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelfInfoSelectCityAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
