//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.qianyue.R.id;
import com.internet.qianyue.R.layout;
import com.internet.view.CircleImageView;
import com.internet.view.HeaderView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SelfInfoEditAct_
    extends SelfInfoEditAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_self_info_edit);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelfInfoEditAct_.IntentBuilder_ intent(Context context) {
        return new SelfInfoEditAct_.IntentBuilder_(context);
    }

    public static SelfInfoEditAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SelfInfoEditAct_.IntentBuilder_(fragment);
    }

    public static SelfInfoEditAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SelfInfoEditAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_home = ((EditText) hasViews.findViewById(id.text_home));
        text_birthday = ((TextView) hasViews.findViewById(id.text_birthday));
        text_age = ((EditText) hasViews.findViewById(id.text_age));
        image_header = ((CircleImageView) hasViews.findViewById(id.image_header));
        text_sex = ((TextView) hasViews.findViewById(id.text_sex));
        text_address = ((TextView) hasViews.findViewById(id.text_address));
        text_school = ((EditText) hasViews.findViewById(id.text_school));
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        {
            View view = hasViews.findViewById(id.view_address);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfInfoEditAct_.this.clickAddress();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_image_header);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfInfoEditAct_.this.clickViewImageHeader();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_birthday);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfInfoEditAct_.this.clickBirthday();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_sex);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfInfoEditAct_.this.clickSex();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.text_header_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfInfoEditAct_.this.clickSave();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void showLoading(final String tip) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.showLoading(tip);
            }

        }
        );
    }

    @Override
    public void showToast(final String content) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.showToast(content);
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean enable) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.fullScreen(enable);
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException ex) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.onApiException(ex);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void doOk() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.doOk();
            }

        }
        );
    }

    @Override
    public void initView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.initView();
            }

        }
        );
    }

    @Override
    public void showHead(final boolean isShow, final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfInfoEditAct_.super.showHead(isShow, bitmap);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoEditAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void showHead() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoEditAct_.super.showHead();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doSave() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoEditAct_.super.doSave();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void saveMyBitmap(final String fileName, final Bitmap mBitmap, final int quality) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfInfoEditAct_.super.saveMyBitmap(fileName, mBitmap, quality);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelfInfoEditAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfInfoEditAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfInfoEditAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelfInfoEditAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
