//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.internet.http.api.ApiException;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import com.internet.view.CircleImageView;
import com.internet.view.HeaderView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SelfCenterAct_
    extends SelfCenterAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_self_center);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelfCenterAct_.IntentBuilder_ intent(Context context) {
        return new SelfCenterAct_.IntentBuilder_(context);
    }

    public static SelfCenterAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SelfCenterAct_.IntentBuilder_(fragment);
    }

    public static SelfCenterAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SelfCenterAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        text_teacher_state = ((TextView) hasViews.findViewById(id.text_teacher_state));
        text_phone = ((TextView) hasViews.findViewById(id.text_phone));
        image_header = ((CircleImageView) hasViews.findViewById(id.image_header));
        text_name = ((TextView) hasViews.findViewById(id.text_name));
        {
            View view = hasViews.findViewById(id.view_teacher);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickTeacher();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_self);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickSelf();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_safe);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickSafe();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_help);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickHelp();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_about);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickAbout();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_exit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfCenterAct_.this.clickExit();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void showHead(final boolean isShow, final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.showHead(isShow, bitmap);
            }

        }
        );
    }

    @Override
    public void initUserView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfCenterAct_.super.initUserView();
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfCenterAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void findUser() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfCenterAct_.super.findUser();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void findUser2() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfCenterAct_.super.findUser2();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void showHead() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfCenterAct_.super.showHead();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelfCenterAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfCenterAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfCenterAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelfCenterAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
