//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act;

import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemSelectedListener;
import android.widget.EditText;
import android.widget.Spinner;
import com.internet.http.api.ApiException;
import com.internet.http.data.vo.SelectSysTypeVO;
import com.internet.turnright.b.R.layout;
import com.internet.view.HeaderView;
import com.internet.view.PaperItemView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SelfTeacherEditAct_
    extends SelfTeacherEditAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_self_teacher_edit);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelfTeacherEditAct_.IntentBuilder_ intent(Context context) {
        return new SelfTeacherEditAct_.IntentBuilder_(context);
    }

    public static SelfTeacherEditAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SelfTeacherEditAct_.IntentBuilder_(fragment);
    }

    public static SelfTeacherEditAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SelfTeacherEditAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_carNo = ((EditText) hasViews.findViewById(com.internet.turnright.b.R.id.text_carNo));
        paper5 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper5));
        paper3 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper3));
        text_no = ((EditText) hasViews.findViewById(com.internet.turnright.b.R.id.text_no));
        text_name = ((EditText) hasViews.findViewById(com.internet.turnright.b.R.id.text_name));
        paper4 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper4));
        paper2 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper2));
        paper6 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper6));
        mCarType = ((Spinner) hasViews.findViewById(com.internet.turnright.b.R.id.mCarType));
        view_header = ((HeaderView) hasViews.findViewById(com.internet.turnright.b.R.id.view_header));
        paper1 = ((PaperItemView) hasViews.findViewById(com.internet.turnright.b.R.id.paper1));
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.text_header_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickSubmit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper4);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper5);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.paper6);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SelfTeacherEditAct_.this.clickPaper(view);
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.internet.turnright.b.R.id.mCarType));
            if (view!= null) {
                view.setOnItemSelectedListener(new OnItemSelectedListener() {


                    @Override
                    public void onNothingSelected(AdapterView<?> parent) {
                        itemSelectCity(false, -1);
                    }

                    @Override
                    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                        SelfTeacherEditAct_.this.itemSelectCity(true, position);
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void closeInputKeyboard() {
        handler_.postDelayed(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.closeInputKeyboard();
            }

        }
        , 200L);
    }

    @Override
    public void fullScreen(final boolean arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.fullScreen(arg0);
            }

        }
        );
    }

    @Override
    public void closeLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.closeLoading();
            }

        }
        );
    }

    @Override
    public void onApiException(final ApiException arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.onApiException(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.showLoading(arg0);
            }

        }
        );
    }

    @Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.showLoading();
            }

        }
        );
    }

    @Override
    public void showToast(final String arg0) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.showToast(arg0);
            }

        }
        );
    }

    @Override
    public void submit() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.submit();
            }

        }
        );
    }

    @Override
    public void doOk() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.doOk();
            }

        }
        );
    }

    @Override
    public void initView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.initView();
            }

        }
        );
    }

    @Override
    public void showHead(final int position, final Bitmap bitmap) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.showHead(position, bitmap);
            }

        }
        );
    }

    @Override
    public void showCarType(final ArrayList<SelectSysTypeVO> listSelectSysTypeVO) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                SelfTeacherEditAct_.super.showCarType(listSelectSysTypeVO);
            }

        }
        );
    }

    @Override
    public void doBack() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.doBack();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getCarType() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.getCarType();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getAuthInfo() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.getAuthInfo();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void submitPhoto(final int index) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.submitPhoto(index);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void showHead(final String url, final int position) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.showHead(url, position);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doSubmit() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.doSubmit();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void saveMyBitmap(final String fileName, final Bitmap mBitmap, final int quality) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelfTeacherEditAct_.super.saveMyBitmap(fileName, mBitmap, quality);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelfTeacherEditAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfTeacherEditAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SelfTeacherEditAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelfTeacherEditAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
