//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.act.qianyue;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import com.internet.view.HeaderView;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PoorPeopleDetailAct_
    extends PoorPeopleDetailAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.act_poor_people_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PoorPeopleDetailAct_.IntentBuilder_ intent(Context context) {
        return new PoorPeopleDetailAct_.IntentBuilder_(context);
    }

    public static PoorPeopleDetailAct_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PoorPeopleDetailAct_.IntentBuilder_(fragment);
    }

    public static PoorPeopleDetailAct_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PoorPeopleDetailAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        id_text3 = ((TextView) hasViews.findViewById(id.id_text3));
        id_text1 = ((TextView) hasViews.findViewById(id.id_text1));
        id_text4 = ((TextView) hasViews.findViewById(id.id_text4));
        mPageVp = ((ViewPager) hasViews.findViewById(id.id_page_vp));
        id_text2 = ((TextView) hasViews.findViewById(id.id_text2));
        view_header = ((HeaderView) hasViews.findViewById(id.view_header));
        {
            View view = hasViews.findViewById(id.id_text3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PoorPeopleDetailAct_.this.clickText3();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.id_text1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PoorPeopleDetailAct_.this.clickText1();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.id_text2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PoorPeopleDetailAct_.this.clickText2();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.id_text4);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PoorPeopleDetailAct_.this.clickText4();
                    }

                }
                );
            }
        }
        init();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PoorPeopleDetailAct_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PoorPeopleDetailAct_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PoorPeopleDetailAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PoorPeopleDetailAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
