//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.view;

import android.content.Context;
import android.util.AttributeSet;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class DialogBgView_
    extends DialogBgView
    implements HasViews
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public DialogBgView_(Context context) {
        super(context);
        init_();
    }

    public DialogBgView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public DialogBgView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static DialogBgView build(Context context) {
        DialogBgView_ instance = new DialogBgView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static DialogBgView build(Context context, AttributeSet attrs) {
        DialogBgView_ instance = new DialogBgView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static DialogBgView build(Context context, AttributeSet attrs, int defStyle) {
        DialogBgView_ instance = new DialogBgView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

}
