//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.view;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.TextView;
import com.internet.qianyue.R.id;
import com.internet.qianyue.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class HeaderView_
    extends HeaderView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public HeaderView_(Context context) {
        super(context);
        init_();
    }

    public HeaderView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public HeaderView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static HeaderView build(Context context) {
        HeaderView_ instance = new HeaderView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_header, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static HeaderView build(Context context, AttributeSet attrs) {
        HeaderView_ instance = new HeaderView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static HeaderView build(Context context, AttributeSet attrs, int defStyle) {
        HeaderView_ instance = new HeaderView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        image_back = ((ImageView) hasViews.findViewById(id.image_back));
        image_header_right = ((ImageView) hasViews.findViewById(id.image_header_right));
        text_header_right = ((TextView) hasViews.findViewById(id.text_header_right));
        text_title = ((TextView) hasViews.findViewById(id.text_title));
        {
            View view = hasViews.findViewById(id.image_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HeaderView_.this.back();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void back() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    HeaderView_.super.back();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

}
