//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.view;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.TextView;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class HeaderViewMainOrder_
    extends HeaderViewMainOrder
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public HeaderViewMainOrder_(Context context) {
        super(context);
        init_();
    }

    public HeaderViewMainOrder_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public HeaderViewMainOrder_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static HeaderViewMainOrder build(Context context) {
        HeaderViewMainOrder_ instance = new HeaderViewMainOrder_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_header_order_main, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static HeaderViewMainOrder build(Context context, AttributeSet attrs) {
        HeaderViewMainOrder_ instance = new HeaderViewMainOrder_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static HeaderViewMainOrder build(Context context, AttributeSet attrs, int defStyle) {
        HeaderViewMainOrder_ instance = new HeaderViewMainOrder_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        text_title_3 = ((TextView) hasViews.findViewById(id.text_title_3));
        view_bottom_1 = ((View) hasViews.findViewById(id.view_bottom_1));
        view_bottom_2 = ((View) hasViews.findViewById(id.view_bottom_2));
        text_title_2 = ((TextView) hasViews.findViewById(id.text_title_2));
        text_title_1 = ((TextView) hasViews.findViewById(id.text_title_1));
        image_back = ((ImageView) hasViews.findViewById(id.image_back));
        view_bottom_3 = ((View) hasViews.findViewById(id.view_bottom_3));
        {
            View view = hasViews.findViewById(id.title2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HeaderViewMainOrder_.this.click2();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.image_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HeaderViewMainOrder_.this.back();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.title3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HeaderViewMainOrder_.this.click3();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.title1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HeaderViewMainOrder_.this.click1();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void back() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    HeaderViewMainOrder_.super.back();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

}
