//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.view;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.TextView;
import com.internet.turnright.b.R.id;
import com.internet.turnright.b.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MainOrderDateItemView_
    extends MainOrderDateItemView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public MainOrderDateItemView_(Context context) {
        super(context);
        init_();
    }

    public MainOrderDateItemView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static MainOrderDateItemView build(Context context) {
        MainOrderDateItemView_ instance = new MainOrderDateItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_order_main_date_item, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static MainOrderDateItemView build(Context context, AttributeSet attrs) {
        MainOrderDateItemView_ instance = new MainOrderDateItemView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        order_quantity = ((TextView) hasViews.findViewById(id.order_quantity));
        text_date = ((TextView) hasViews.findViewById(id.text_date));
        text_today = ((TextView) hasViews.findViewById(id.text_today));
        init();
    }

}
