//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.internet.dialog;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TimePicker;
import com.internet.turnright.b.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class DialogSelectTime_
    extends DialogSelectTime
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.dialog_select_time, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static DialogSelectTime_.FragmentBuilder_ builder() {
        return new DialogSelectTime_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_ensure = ((Button) hasViews.findViewById(com.internet.turnright.b.R.id.btn_ensure));
        mTimePiker = ((TimePicker) hasViews.findViewById(com.internet.turnright.b.R.id.mTimePiker));
        btn_cancel = ((Button) hasViews.findViewById(com.internet.turnright.b.R.id.btn_cancel));
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.btn_ensure);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DialogSelectTime_.this.ensure();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.internet.turnright.b.R.id.btn_cancel);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DialogSelectTime_.this.cancel();
                    }

                }
                );
            }
        }
        init();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public DialogSelectTime build() {
            DialogSelectTime_ fragment_ = new DialogSelectTime_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
